FROM python:3.11-slim

USER root
RUN apt-get update && apt-get install -y gcc python3-dev

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY src src
COPY .env .env

WORKDIR /src

EXPOSE 8000

CMD ["uvicorn" , "app:app" , "--reload", "--host", "0.0.0.0", "--port", "8000"]